### ISSUE TITLE
Infografia- Adriana Hernandez Martinez

### ISSUE THREAD

**Issue by AdriHernandez-Martinez08** [SistemasTecTlaxiaco/actividad-1-infografia-AdriHernandez-Martinez08#1]
[Infografía-Ciclo de vida de un Sistema de Software.pdf](https://github.com/user-attachments/files/16808904/Infografia-Ciclo.de.vida.de.un.Sistema.de.Software.pdf)

**Comment by EdgarExa** [comment]
20 DE 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
